FROM python:3.11-slim
RUN apt-get update && apt-get install -y wget curl gnupg \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt
RUN playwright install --with-deps chromium firefox webkit
COPY . .
ENV ENV=qa PYTHONPATH=/app
CMD ["pytest", "-v", "--alluredir=allure-results"]