[pytest]
minversion = 7.4
testpaths = tests/functional tests/api
python_files = test_*.py
addopts = 
    -v
    --browser=chromium
    --alluredir=allure-results
    --html=reports/report.html
    --self-contained-html
    --strict-markers
markers =
    smoke: 冒烟测试
    api: API测试